### ISSUE TITLE
box_check_update

### ISSUE THREAD

**Issue by patrikgafvert** [menacit/practical_cryptography_course#3]
Add this following line to Vagrantfile to disable the box upgrade check.
config.vm.box_check_update = false

I will update the system within the system, with 
```sudo apt -y update && sudo apt -y upgrade```
instead

**Comment by Doctor-love** [comment]
Good point - feel free to submit a pull request! Otherwise I'll just add the change myself.

**Comment by Doctor-love** [comment]
Fixed!
